-- Reference tables, weapon properties, masteries and poisons
-- Generated by scripts/srd/build-srd-seed.mjs from 5e-bits/5e-srd-api @ 05c109ea1f6b5445960b645ded48ad9c6a8df7b0
-- (packages/5e-database/src/2024/en). Do not edit by hand; re-run the script instead.
--
-- This work includes material from the System Reference Document 5.2.1 ("SRD 5.2.1") by
-- Wizards of the Coast LLC, available at https://www.dndbeyond.com/srd. The SRD 5.2.1 is
-- licensed under the Creative Commons Attribution 4.0 International License, available at
-- https://creativecommons.org/licenses/by/4.0/legalcode.

INSERT INTO Source (sourceName, sourceAbbrev, sourceLicense, sourceLicenseUrl, sourceAttribution, sourceUrl) VALUES ('System Reference Document 5.2.1', 'SRD 5.2.1', 'CC-BY-4.0', 'https://creativecommons.org/licenses/by/4.0/legalcode', 'This work includes material from the System Reference Document 5.2.1 ("SRD 5.2.1") by Wizards of the Coast LLC, available at https://www.dndbeyond.com/srd. The SRD 5.2.1 is licensed under the Creative Commons Attribution 4.0 International License, available at https://creativecommons.org/licenses/by/4.0/legalcode.', 'https://www.dndbeyond.com/srd')
  ON CONFLICT (sourceAbbrev) DO UPDATE SET sourceName = excluded.sourceName, sourceLicense = excluded.sourceLicense, sourceLicenseUrl = excluded.sourceLicenseUrl, sourceAttribution = excluded.sourceAttribution, sourceUrl = excluded.sourceUrl;
INSERT INTO Ability (abilityCode, abilityName, sortOrder) VALUES ('STR', 'Strength', 1)
  ON CONFLICT (abilityCode) DO UPDATE SET abilityName = excluded.abilityName, sortOrder = excluded.sortOrder;
INSERT INTO Ability (abilityCode, abilityName, sortOrder) VALUES ('DEX', 'Dexterity', 2)
  ON CONFLICT (abilityCode) DO UPDATE SET abilityName = excluded.abilityName, sortOrder = excluded.sortOrder;
INSERT INTO Ability (abilityCode, abilityName, sortOrder) VALUES ('CON', 'Constitution', 3)
  ON CONFLICT (abilityCode) DO UPDATE SET abilityName = excluded.abilityName, sortOrder = excluded.sortOrder;
INSERT INTO Ability (abilityCode, abilityName, sortOrder) VALUES ('INT', 'Intelligence', 4)
  ON CONFLICT (abilityCode) DO UPDATE SET abilityName = excluded.abilityName, sortOrder = excluded.sortOrder;
INSERT INTO Ability (abilityCode, abilityName, sortOrder) VALUES ('WIS', 'Wisdom', 5)
  ON CONFLICT (abilityCode) DO UPDATE SET abilityName = excluded.abilityName, sortOrder = excluded.sortOrder;
INSERT INTO Ability (abilityCode, abilityName, sortOrder) VALUES ('CHA', 'Charisma', 6)
  ON CONFLICT (abilityCode) DO UPDATE SET abilityName = excluded.abilityName, sortOrder = excluded.sortOrder;
INSERT INTO Skill (skillName, skillSlug, abilityID, skillDescription) VALUES ('Acrobatics', 'acrobatics', (SELECT abilityID FROM Ability WHERE abilityCode = 'DEX'), 'Stay on your feet in a tricky situation, or perform an acrobatic stunt.')
  ON CONFLICT (skillSlug) DO UPDATE SET skillName = excluded.skillName, abilityID = excluded.abilityID, skillDescription = excluded.skillDescription;
INSERT INTO Skill (skillName, skillSlug, abilityID, skillDescription) VALUES ('Animal Handling', 'animal-handling', (SELECT abilityID FROM Ability WHERE abilityCode = 'WIS'), 'Calm or train an animal, or get an animal to behave in a certain way.')
  ON CONFLICT (skillSlug) DO UPDATE SET skillName = excluded.skillName, abilityID = excluded.abilityID, skillDescription = excluded.skillDescription;
INSERT INTO Skill (skillName, skillSlug, abilityID, skillDescription) VALUES ('Arcana', 'arcana', (SELECT abilityID FROM Ability WHERE abilityCode = 'INT'), 'Recall lore about spells, magic items, and the planes of existence.')
  ON CONFLICT (skillSlug) DO UPDATE SET skillName = excluded.skillName, abilityID = excluded.abilityID, skillDescription = excluded.skillDescription;
INSERT INTO Skill (skillName, skillSlug, abilityID, skillDescription) VALUES ('Athletics', 'athletics', (SELECT abilityID FROM Ability WHERE abilityCode = 'STR'), 'Jump farther than normal, stay afloat in rough water, or break something.')
  ON CONFLICT (skillSlug) DO UPDATE SET skillName = excluded.skillName, abilityID = excluded.abilityID, skillDescription = excluded.skillDescription;
INSERT INTO Skill (skillName, skillSlug, abilityID, skillDescription) VALUES ('Deception', 'deception', (SELECT abilityID FROM Ability WHERE abilityCode = 'CHA'), 'Tell a convincing lie, or wear a disguise convincingly.')
  ON CONFLICT (skillSlug) DO UPDATE SET skillName = excluded.skillName, abilityID = excluded.abilityID, skillDescription = excluded.skillDescription;
INSERT INTO Skill (skillName, skillSlug, abilityID, skillDescription) VALUES ('History', 'history', (SELECT abilityID FROM Ability WHERE abilityCode = 'INT'), 'Recall lore about historical events, people, nations, and cultures.')
  ON CONFLICT (skillSlug) DO UPDATE SET skillName = excluded.skillName, abilityID = excluded.abilityID, skillDescription = excluded.skillDescription;
INSERT INTO Skill (skillName, skillSlug, abilityID, skillDescription) VALUES ('Insight', 'insight', (SELECT abilityID FROM Ability WHERE abilityCode = 'WIS'), 'Discern a person’s mood and intentions.')
  ON CONFLICT (skillSlug) DO UPDATE SET skillName = excluded.skillName, abilityID = excluded.abilityID, skillDescription = excluded.skillDescription;
INSERT INTO Skill (skillName, skillSlug, abilityID, skillDescription) VALUES ('Intimidation', 'intimidation', (SELECT abilityID FROM Ability WHERE abilityCode = 'CHA'), 'Awe or threaten someone into doing what you want.')
  ON CONFLICT (skillSlug) DO UPDATE SET skillName = excluded.skillName, abilityID = excluded.abilityID, skillDescription = excluded.skillDescription;
INSERT INTO Skill (skillName, skillSlug, abilityID, skillDescription) VALUES ('Investigation', 'investigation', (SELECT abilityID FROM Ability WHERE abilityCode = 'INT'), 'Find obscure information in books, or deduce how something works.')
  ON CONFLICT (skillSlug) DO UPDATE SET skillName = excluded.skillName, abilityID = excluded.abilityID, skillDescription = excluded.skillDescription;
INSERT INTO Skill (skillName, skillSlug, abilityID, skillDescription) VALUES ('Medicine', 'medicine', (SELECT abilityID FROM Ability WHERE abilityCode = 'WIS'), 'Diagnose an illness, or determine what killed the recently slain.')
  ON CONFLICT (skillSlug) DO UPDATE SET skillName = excluded.skillName, abilityID = excluded.abilityID, skillDescription = excluded.skillDescription;
INSERT INTO Skill (skillName, skillSlug, abilityID, skillDescription) VALUES ('Nature', 'nature', (SELECT abilityID FROM Ability WHERE abilityCode = 'INT'), 'Recall lore about terrain, plants, animals, and weather.')
  ON CONFLICT (skillSlug) DO UPDATE SET skillName = excluded.skillName, abilityID = excluded.abilityID, skillDescription = excluded.skillDescription;
INSERT INTO Skill (skillName, skillSlug, abilityID, skillDescription) VALUES ('Perception', 'perception', (SELECT abilityID FROM Ability WHERE abilityCode = 'WIS'), 'Using a combination of senses, notice something that’s easy to miss.')
  ON CONFLICT (skillSlug) DO UPDATE SET skillName = excluded.skillName, abilityID = excluded.abilityID, skillDescription = excluded.skillDescription;
INSERT INTO Skill (skillName, skillSlug, abilityID, skillDescription) VALUES ('Performance', 'performance', (SELECT abilityID FROM Ability WHERE abilityCode = 'CHA'), 'Act, tell a story, perform music, or dance.')
  ON CONFLICT (skillSlug) DO UPDATE SET skillName = excluded.skillName, abilityID = excluded.abilityID, skillDescription = excluded.skillDescription;
INSERT INTO Skill (skillName, skillSlug, abilityID, skillDescription) VALUES ('Persuasion', 'persuasion', (SELECT abilityID FROM Ability WHERE abilityCode = 'CHA'), 'Honestly and graciously convince someone of something.')
  ON CONFLICT (skillSlug) DO UPDATE SET skillName = excluded.skillName, abilityID = excluded.abilityID, skillDescription = excluded.skillDescription;
INSERT INTO Skill (skillName, skillSlug, abilityID, skillDescription) VALUES ('Religion', 'religion', (SELECT abilityID FROM Ability WHERE abilityCode = 'INT'), 'Recall lore about gods, religious rituals, and holy symbols.')
  ON CONFLICT (skillSlug) DO UPDATE SET skillName = excluded.skillName, abilityID = excluded.abilityID, skillDescription = excluded.skillDescription;
INSERT INTO Skill (skillName, skillSlug, abilityID, skillDescription) VALUES ('Sleight of Hand', 'sleight-of-hand', (SELECT abilityID FROM Ability WHERE abilityCode = 'DEX'), 'Pick a pocket, conceal a handheld object, or perform legerdemain.')
  ON CONFLICT (skillSlug) DO UPDATE SET skillName = excluded.skillName, abilityID = excluded.abilityID, skillDescription = excluded.skillDescription;
INSERT INTO Skill (skillName, skillSlug, abilityID, skillDescription) VALUES ('Stealth', 'stealth', (SELECT abilityID FROM Ability WHERE abilityCode = 'DEX'), 'Escape notice by moving quietly and hiding behind things.')
  ON CONFLICT (skillSlug) DO UPDATE SET skillName = excluded.skillName, abilityID = excluded.abilityID, skillDescription = excluded.skillDescription;
INSERT INTO Skill (skillName, skillSlug, abilityID, skillDescription) VALUES ('Survival', 'survival', (SELECT abilityID FROM Ability WHERE abilityCode = 'WIS'), 'Follow tracks, forage, find a trail, or avoid natural hazards.')
  ON CONFLICT (skillSlug) DO UPDATE SET skillName = excluded.skillName, abilityID = excluded.abilityID, skillDescription = excluded.skillDescription;
INSERT INTO DamageType (damageTypeName, damageTypeDescription) VALUES ('Acid', 'Corrosive liquids, digestive enzymes')
  ON CONFLICT (damageTypeName) DO UPDATE SET damageTypeDescription = excluded.damageTypeDescription;
INSERT INTO DamageType (damageTypeName, damageTypeDescription) VALUES ('Bludgeoning', 'Blunt objects, constriction, falling')
  ON CONFLICT (damageTypeName) DO UPDATE SET damageTypeDescription = excluded.damageTypeDescription;
INSERT INTO DamageType (damageTypeName, damageTypeDescription) VALUES ('Cold', 'Freezing water, icy blasts')
  ON CONFLICT (damageTypeName) DO UPDATE SET damageTypeDescription = excluded.damageTypeDescription;
INSERT INTO DamageType (damageTypeName, damageTypeDescription) VALUES ('Fire', 'Flames, unbearable heat')
  ON CONFLICT (damageTypeName) DO UPDATE SET damageTypeDescription = excluded.damageTypeDescription;
INSERT INTO DamageType (damageTypeName, damageTypeDescription) VALUES ('Force', 'Pure magical energy')
  ON CONFLICT (damageTypeName) DO UPDATE SET damageTypeDescription = excluded.damageTypeDescription;
INSERT INTO DamageType (damageTypeName, damageTypeDescription) VALUES ('Lightning', 'Electricity')
  ON CONFLICT (damageTypeName) DO UPDATE SET damageTypeDescription = excluded.damageTypeDescription;
INSERT INTO DamageType (damageTypeName, damageTypeDescription) VALUES ('Necrotic', 'Life-draining energy')
  ON CONFLICT (damageTypeName) DO UPDATE SET damageTypeDescription = excluded.damageTypeDescription;
INSERT INTO DamageType (damageTypeName, damageTypeDescription) VALUES ('Piercing', 'Fangs, puncturing objects')
  ON CONFLICT (damageTypeName) DO UPDATE SET damageTypeDescription = excluded.damageTypeDescription;
INSERT INTO DamageType (damageTypeName, damageTypeDescription) VALUES ('Poison', 'Toxic gas, venom')
  ON CONFLICT (damageTypeName) DO UPDATE SET damageTypeDescription = excluded.damageTypeDescription;
INSERT INTO DamageType (damageTypeName, damageTypeDescription) VALUES ('Psychic', 'Mind-rending energy')
  ON CONFLICT (damageTypeName) DO UPDATE SET damageTypeDescription = excluded.damageTypeDescription;
INSERT INTO DamageType (damageTypeName, damageTypeDescription) VALUES ('Radiant', 'Holy energy, searing radiation')
  ON CONFLICT (damageTypeName) DO UPDATE SET damageTypeDescription = excluded.damageTypeDescription;
INSERT INTO DamageType (damageTypeName, damageTypeDescription) VALUES ('Slashing', 'Claws, cutting objects')
  ON CONFLICT (damageTypeName) DO UPDATE SET damageTypeDescription = excluded.damageTypeDescription;
INSERT INTO DamageType (damageTypeName, damageTypeDescription) VALUES ('Thunder', 'Concussive sound')
  ON CONFLICT (damageTypeName) DO UPDATE SET damageTypeDescription = excluded.damageTypeDescription;
INSERT INTO Condition (conditionName, conditionSlug, conditionDescription, sourceID) VALUES ('Blinded', 'blinded', 'While you have the Blinded condition, you experience the following effects.
**Can''t See.** You can''t see and automatically fail any ability check that requires sight.
**Attacks Affected.** Attack rolls against you have Advantage, and your attack rolls have Disadvantage.', (SELECT sourceID FROM Source WHERE sourceAbbrev = 'SRD 5.2.1'))
  ON CONFLICT (conditionSlug) DO UPDATE SET conditionName = excluded.conditionName, conditionDescription = excluded.conditionDescription, sourceID = excluded.sourceID;
INSERT INTO Condition (conditionName, conditionSlug, conditionDescription, sourceID) VALUES ('Charmed', 'charmed', 'While you have the Charmed condition, you experience the following effects.
**Can''t Harm the Charmer.** You can''t attack the charmer or target the charmer with damaging abilities or magical effects.
**Social Advantage.** The charmer has Advantage on ability checks to interact socially with you.', (SELECT sourceID FROM Source WHERE sourceAbbrev = 'SRD 5.2.1'))
  ON CONFLICT (conditionSlug) DO UPDATE SET conditionName = excluded.conditionName, conditionDescription = excluded.conditionDescription, sourceID = excluded.sourceID;
INSERT INTO Condition (conditionName, conditionSlug, conditionDescription, sourceID) VALUES ('Deafened', 'deafened', 'While you have the Deafened condition, you experience the following effect.
**Can''t Hear.** You can''t hear and automatically fail any ability check that requires hearing.', (SELECT sourceID FROM Source WHERE sourceAbbrev = 'SRD 5.2.1'))
  ON CONFLICT (conditionSlug) DO UPDATE SET conditionName = excluded.conditionName, conditionDescription = excluded.conditionDescription, sourceID = excluded.sourceID;
INSERT INTO Condition (conditionName, conditionSlug, conditionDescription, sourceID) VALUES ('Exhaustion', 'exhaustion', 'While you have the Exhaustion condition, you experience the following effects.
**Exhaustion Levels.** This condition is cumulative. Each time you receive it, you gain 1 Exhaustion level. You die if your Exhaustion level is 6.
**D20 Tests Affected.** When you make a D20 Test, the roll is reduced by 2 times your Exhaustion level.
**Speed Reduced.** Your Speed is reduced by a number of feet equal to 5 times your Exhaustion level.
**Removing Exhaustion Levels.** Finishing a Long Rest removes 1 of your Exhaustion levels. When your Exhaustion level reaches 0, the condition ends.', (SELECT sourceID FROM Source WHERE sourceAbbrev = 'SRD 5.2.1'))
  ON CONFLICT (conditionSlug) DO UPDATE SET conditionName = excluded.conditionName, conditionDescription = excluded.conditionDescription, sourceID = excluded.sourceID;
INSERT INTO Condition (conditionName, conditionSlug, conditionDescription, sourceID) VALUES ('Frightened', 'frightened', 'While you have the Frightened condition, you experience the following effects.
**Ability Checks and Attacks Affected.** You have Disadvantage on ability checks and attack rolls while the source of fear is within line of sight.
**Can''t Approach.** You can''t willingly move closer to the source of your fear.', (SELECT sourceID FROM Source WHERE sourceAbbrev = 'SRD 5.2.1'))
  ON CONFLICT (conditionSlug) DO UPDATE SET conditionName = excluded.conditionName, conditionDescription = excluded.conditionDescription, sourceID = excluded.sourceID;
INSERT INTO Condition (conditionName, conditionSlug, conditionDescription, sourceID) VALUES ('Grappled', 'grappled', 'While you have the Grappled condition, you experience the following effects.
**Speed 0.** Your Speed is 0 and can''t increase.
**Attacks Affected.** You have Disadvantage on attack rolls against any target other than the grappler.
**Movable.** The grappler can drag or carry you when it moves, but every foot of movement costs it 1 extra foot unless you are Tiny or two or more sizes smaller.', (SELECT sourceID FROM Source WHERE sourceAbbrev = 'SRD 5.2.1'))
  ON CONFLICT (conditionSlug) DO UPDATE SET conditionName = excluded.conditionName, conditionDescription = excluded.conditionDescription, sourceID = excluded.sourceID;
INSERT INTO Condition (conditionName, conditionSlug, conditionDescription, sourceID) VALUES ('Incapacitated', 'incapacitated', 'While you have the Incapacitated condition, you experience the following effects.
**Inactive.** You can''t take any action, Bonus Action, or Reaction.
**No Concentration.** Your Concentration is broken.
**Speechless.** You can''t speak.
**Surprised.** If you''re Incapacitated when you roll Initiative, you have Disadvantage on the roll.', (SELECT sourceID FROM Source WHERE sourceAbbrev = 'SRD 5.2.1'))
  ON CONFLICT (conditionSlug) DO UPDATE SET conditionName = excluded.conditionName, conditionDescription = excluded.conditionDescription, sourceID = excluded.sourceID;
INSERT INTO Condition (conditionName, conditionSlug, conditionDescription, sourceID) VALUES ('Invisible', 'invisible', 'While you have the Invisible condition, you experience the following effects.
**Surprise.** If you''re Invisible when you roll Initiative, you have Advantage on the roll.
**Concealed.** You aren''t affected by any effect that requires its target to be seen unless the effect''s creator can somehow see you. Any equipment you are wearing or carrying is also concealed.
**Attacks Affected.** Attack rolls against you have Disadvantage, and your attack rolls have Advantage. If a creature can somehow see you, you don''t gain this benefit against that creature.', (SELECT sourceID FROM Source WHERE sourceAbbrev = 'SRD 5.2.1'))
  ON CONFLICT (conditionSlug) DO UPDATE SET conditionName = excluded.conditionName, conditionDescription = excluded.conditionDescription, sourceID = excluded.sourceID;
INSERT INTO Condition (conditionName, conditionSlug, conditionDescription, sourceID) VALUES ('Paralyzed', 'paralyzed', 'While you have the Paralyzed condition, you experience the following effects.
**Incapacitated.** You have the Incapacitated condition.
**Speed 0.** Your Speed is 0 and can''t increase.
**Saving Throws Affected.** You automatically fail Strength and Dexterity saving throws.
**Attacks Affected.** Attack rolls against you have Advantage.
**Automatic Critical Hits.** Any attack roll that hits you is a Critical Hit if the attacker is within 5 feet of you.', (SELECT sourceID FROM Source WHERE sourceAbbrev = 'SRD 5.2.1'))
  ON CONFLICT (conditionSlug) DO UPDATE SET conditionName = excluded.conditionName, conditionDescription = excluded.conditionDescription, sourceID = excluded.sourceID;
INSERT INTO Condition (conditionName, conditionSlug, conditionDescription, sourceID) VALUES ('Petrified', 'petrified', 'While you have the Petrified condition, you experience the following effects.
**Turned to Inanimate Substance.** You are transformed, along with any nonmagical objects you are wearing and carrying, into a solid inanimate substance (usually stone). Your weight increases by a factor of ten, and you cease aging.
**Incapacitated.** You have the Incapacitated condition.
**Speed 0.** Your Speed is 0 and can''t increase.
**Attacks Affected.** Attack rolls against you have Advantage.
**Saving Throws Affected.** You automatically fail Strength and Dexterity saving throws.
**Resist Damage.** You have Resistance to all damage.
**Poison Immunity.** You have Immunity to the Poisoned condition.
**Saving Throws Affected.** You automatically fail Strength and Dexterity saving throws.
**Resist Damage.** You have Resistance to all damage.
**Poison Immunity.** You have Immunity to the Poisoned condition.', (SELECT sourceID FROM Source WHERE sourceAbbrev = 'SRD 5.2.1'))
  ON CONFLICT (conditionSlug) DO UPDATE SET conditionName = excluded.conditionName, conditionDescription = excluded.conditionDescription, sourceID = excluded.sourceID;
INSERT INTO Condition (conditionName, conditionSlug, conditionDescription, sourceID) VALUES ('Poisoned', 'poisoned', 'While you have the Poisoned condition, you experience the following effect.
**Ability Checks and Attacks Affected.** You have Disadvantage on attack rolls and ability checks.', (SELECT sourceID FROM Source WHERE sourceAbbrev = 'SRD 5.2.1'))
  ON CONFLICT (conditionSlug) DO UPDATE SET conditionName = excluded.conditionName, conditionDescription = excluded.conditionDescription, sourceID = excluded.sourceID;
INSERT INTO Condition (conditionName, conditionSlug, conditionDescription, sourceID) VALUES ('Prone', 'prone', 'While you have the Prone condition, you experience the following effects.
**Restricted Movement.** Your only movement options are to crawl or to spend an amount of movement equal to half your Speed (round down) to right yourself and thereby end the condition. If your Speed is 0, you can''t right yourself.
**Attacks Affected.** You have Disadvantage on attack rolls. An attack roll against you has Advantage if the attacker is within 5 feet of you. Otherwise, that attack roll has Disadvantage.', (SELECT sourceID FROM Source WHERE sourceAbbrev = 'SRD 5.2.1'))
  ON CONFLICT (conditionSlug) DO UPDATE SET conditionName = excluded.conditionName, conditionDescription = excluded.conditionDescription, sourceID = excluded.sourceID;
INSERT INTO Condition (conditionName, conditionSlug, conditionDescription, sourceID) VALUES ('Restrained', 'restrained', 'While you have the Restrained condition, you experience the following effects.
**Speed 0.** Your Speed is 0 and can''t increase.
**Attacks Affected.** Attack rolls against you have Advantage, and your attack rolls have Disadvantage.
**Saving Throws Affected.** You have Disadvantage on Dexterity saving throws.', (SELECT sourceID FROM Source WHERE sourceAbbrev = 'SRD 5.2.1'))
  ON CONFLICT (conditionSlug) DO UPDATE SET conditionName = excluded.conditionName, conditionDescription = excluded.conditionDescription, sourceID = excluded.sourceID;
INSERT INTO Condition (conditionName, conditionSlug, conditionDescription, sourceID) VALUES ('Stunned', 'stunned', 'While you have the Stunned condition, you experience the following effects.
**Incapacitated.** You have the Incapacitated condition.
**Saving Throws Affected.** You automatically fail Strength and Dexterity saving throws.
**Attacks Affected.** Attack rolls against you have Advantage.', (SELECT sourceID FROM Source WHERE sourceAbbrev = 'SRD 5.2.1'))
  ON CONFLICT (conditionSlug) DO UPDATE SET conditionName = excluded.conditionName, conditionDescription = excluded.conditionDescription, sourceID = excluded.sourceID;
INSERT INTO Condition (conditionName, conditionSlug, conditionDescription, sourceID) VALUES ('Unconscious', 'unconscious', 'While you have the Unconscious condition, you experience the following effects.
**Inert.** You have the Incapacitated and Prone conditions, and you drop whatever you''re holding.
**When this condition ends, you remain Prone.
**Speed 0.** Your Speed is 0 and can''t increase.
**Attacks Affected.** Attack rolls against you have Advantage.
**Saving Throws Affected.** You automatically fail Strength and Dexterity saving throws.
**Automatic Critical Hits.** Any attack roll that hits you is a Critical Hit if the attacker is within 5 feet of you.
**Unaware.** You''re unaware of your surroundings.', (SELECT sourceID FROM Source WHERE sourceAbbrev = 'SRD 5.2.1'))
  ON CONFLICT (conditionSlug) DO UPDATE SET conditionName = excluded.conditionName, conditionDescription = excluded.conditionDescription, sourceID = excluded.sourceID;
INSERT INTO CreatureSize (sizeName, sizeSpaceFt, sizeHitDie, sortOrder) VALUES ('Tiny', 2.5, 4, 1)
  ON CONFLICT (sizeName) DO UPDATE SET sizeSpaceFt = excluded.sizeSpaceFt, sizeHitDie = excluded.sizeHitDie, sortOrder = excluded.sortOrder;
INSERT INTO CreatureSize (sizeName, sizeSpaceFt, sizeHitDie, sortOrder) VALUES ('Small', 5, 6, 2)
  ON CONFLICT (sizeName) DO UPDATE SET sizeSpaceFt = excluded.sizeSpaceFt, sizeHitDie = excluded.sizeHitDie, sortOrder = excluded.sortOrder;
INSERT INTO CreatureSize (sizeName, sizeSpaceFt, sizeHitDie, sortOrder) VALUES ('Medium', 5, 8, 3)
  ON CONFLICT (sizeName) DO UPDATE SET sizeSpaceFt = excluded.sizeSpaceFt, sizeHitDie = excluded.sizeHitDie, sortOrder = excluded.sortOrder;
INSERT INTO CreatureSize (sizeName, sizeSpaceFt, sizeHitDie, sortOrder) VALUES ('Large', 10, 10, 4)
  ON CONFLICT (sizeName) DO UPDATE SET sizeSpaceFt = excluded.sizeSpaceFt, sizeHitDie = excluded.sizeHitDie, sortOrder = excluded.sortOrder;
INSERT INTO CreatureSize (sizeName, sizeSpaceFt, sizeHitDie, sortOrder) VALUES ('Huge', 15, 12, 5)
  ON CONFLICT (sizeName) DO UPDATE SET sizeSpaceFt = excluded.sizeSpaceFt, sizeHitDie = excluded.sizeHitDie, sortOrder = excluded.sortOrder;
INSERT INTO CreatureSize (sizeName, sizeSpaceFt, sizeHitDie, sortOrder) VALUES ('Gargantuan', 20, 20, 6)
  ON CONFLICT (sizeName) DO UPDATE SET sizeSpaceFt = excluded.sizeSpaceFt, sizeHitDie = excluded.sizeHitDie, sortOrder = excluded.sortOrder;
INSERT INTO CreatureType (creatureTypeName) VALUES ('Aberration')
  ON CONFLICT (creatureTypeName) DO NOTHING;
INSERT INTO CreatureType (creatureTypeName) VALUES ('Beast')
  ON CONFLICT (creatureTypeName) DO NOTHING;
INSERT INTO CreatureType (creatureTypeName) VALUES ('Celestial')
  ON CONFLICT (creatureTypeName) DO NOTHING;
INSERT INTO CreatureType (creatureTypeName) VALUES ('Construct')
  ON CONFLICT (creatureTypeName) DO NOTHING;
INSERT INTO CreatureType (creatureTypeName) VALUES ('Dragon')
  ON CONFLICT (creatureTypeName) DO NOTHING;
INSERT INTO CreatureType (creatureTypeName) VALUES ('Elemental')
  ON CONFLICT (creatureTypeName) DO NOTHING;
INSERT INTO CreatureType (creatureTypeName) VALUES ('Fey')
  ON CONFLICT (creatureTypeName) DO NOTHING;
INSERT INTO CreatureType (creatureTypeName) VALUES ('Fiend')
  ON CONFLICT (creatureTypeName) DO NOTHING;
INSERT INTO CreatureType (creatureTypeName) VALUES ('Giant')
  ON CONFLICT (creatureTypeName) DO NOTHING;
INSERT INTO CreatureType (creatureTypeName) VALUES ('Humanoid')
  ON CONFLICT (creatureTypeName) DO NOTHING;
INSERT INTO CreatureType (creatureTypeName) VALUES ('Monstrosity')
  ON CONFLICT (creatureTypeName) DO NOTHING;
INSERT INTO CreatureType (creatureTypeName) VALUES ('Ooze')
  ON CONFLICT (creatureTypeName) DO NOTHING;
INSERT INTO CreatureType (creatureTypeName) VALUES ('Plant')
  ON CONFLICT (creatureTypeName) DO NOTHING;
INSERT INTO CreatureType (creatureTypeName) VALUES ('Undead')
  ON CONFLICT (creatureTypeName) DO NOTHING;
INSERT INTO Alignment (alignmentName, alignmentAbbrev) VALUES ('Lawful Good', 'LG')
  ON CONFLICT (alignmentName) DO UPDATE SET alignmentAbbrev = excluded.alignmentAbbrev;
INSERT INTO Alignment (alignmentName, alignmentAbbrev) VALUES ('Neutral Good', 'NG')
  ON CONFLICT (alignmentName) DO UPDATE SET alignmentAbbrev = excluded.alignmentAbbrev;
INSERT INTO Alignment (alignmentName, alignmentAbbrev) VALUES ('Chaotic Good', 'CG')
  ON CONFLICT (alignmentName) DO UPDATE SET alignmentAbbrev = excluded.alignmentAbbrev;
INSERT INTO Alignment (alignmentName, alignmentAbbrev) VALUES ('Lawful Neutral', 'LN')
  ON CONFLICT (alignmentName) DO UPDATE SET alignmentAbbrev = excluded.alignmentAbbrev;
INSERT INTO Alignment (alignmentName, alignmentAbbrev) VALUES ('Neutral', 'N')
  ON CONFLICT (alignmentName) DO UPDATE SET alignmentAbbrev = excluded.alignmentAbbrev;
INSERT INTO Alignment (alignmentName, alignmentAbbrev) VALUES ('Chaotic Neutral', 'CN')
  ON CONFLICT (alignmentName) DO UPDATE SET alignmentAbbrev = excluded.alignmentAbbrev;
INSERT INTO Alignment (alignmentName, alignmentAbbrev) VALUES ('Lawful Evil', 'LE')
  ON CONFLICT (alignmentName) DO UPDATE SET alignmentAbbrev = excluded.alignmentAbbrev;
INSERT INTO Alignment (alignmentName, alignmentAbbrev) VALUES ('Neutral Evil', 'NE')
  ON CONFLICT (alignmentName) DO UPDATE SET alignmentAbbrev = excluded.alignmentAbbrev;
INSERT INTO Alignment (alignmentName, alignmentAbbrev) VALUES ('Chaotic Evil', 'CE')
  ON CONFLICT (alignmentName) DO UPDATE SET alignmentAbbrev = excluded.alignmentAbbrev;
INSERT INTO Alignment (alignmentName, alignmentAbbrev) VALUES ('Unaligned', 'U')
  ON CONFLICT (alignmentName) DO UPDATE SET alignmentAbbrev = excluded.alignmentAbbrev;
INSERT INTO Language (languageName, languageKind, languageOrigin, sourceID) VALUES ('Common', 'standard', NULL, (SELECT sourceID FROM Source WHERE sourceAbbrev = 'SRD 5.2.1'))
  ON CONFLICT (languageName) DO UPDATE SET languageKind = excluded.languageKind, languageOrigin = excluded.languageOrigin, sourceID = excluded.sourceID;
INSERT INTO Language (languageName, languageKind, languageOrigin, sourceID) VALUES ('Common Sign Language', 'standard', NULL, (SELECT sourceID FROM Source WHERE sourceAbbrev = 'SRD 5.2.1'))
  ON CONFLICT (languageName) DO UPDATE SET languageKind = excluded.languageKind, languageOrigin = excluded.languageOrigin, sourceID = excluded.sourceID;
INSERT INTO Language (languageName, languageKind, languageOrigin, sourceID) VALUES ('Draconic', 'standard', NULL, (SELECT sourceID FROM Source WHERE sourceAbbrev = 'SRD 5.2.1'))
  ON CONFLICT (languageName) DO UPDATE SET languageKind = excluded.languageKind, languageOrigin = excluded.languageOrigin, sourceID = excluded.sourceID;
INSERT INTO Language (languageName, languageKind, languageOrigin, sourceID) VALUES ('Dwarvish', 'standard', NULL, (SELECT sourceID FROM Source WHERE sourceAbbrev = 'SRD 5.2.1'))
  ON CONFLICT (languageName) DO UPDATE SET languageKind = excluded.languageKind, languageOrigin = excluded.languageOrigin, sourceID = excluded.sourceID;
INSERT INTO Language (languageName, languageKind, languageOrigin, sourceID) VALUES ('Elvish', 'standard', NULL, (SELECT sourceID FROM Source WHERE sourceAbbrev = 'SRD 5.2.1'))
  ON CONFLICT (languageName) DO UPDATE SET languageKind = excluded.languageKind, languageOrigin = excluded.languageOrigin, sourceID = excluded.sourceID;
INSERT INTO Language (languageName, languageKind, languageOrigin, sourceID) VALUES ('Giant', 'standard', NULL, (SELECT sourceID FROM Source WHERE sourceAbbrev = 'SRD 5.2.1'))
  ON CONFLICT (languageName) DO UPDATE SET languageKind = excluded.languageKind, languageOrigin = excluded.languageOrigin, sourceID = excluded.sourceID;
INSERT INTO Language (languageName, languageKind, languageOrigin, sourceID) VALUES ('Gnomish', 'standard', NULL, (SELECT sourceID FROM Source WHERE sourceAbbrev = 'SRD 5.2.1'))
  ON CONFLICT (languageName) DO UPDATE SET languageKind = excluded.languageKind, languageOrigin = excluded.languageOrigin, sourceID = excluded.sourceID;
INSERT INTO Language (languageName, languageKind, languageOrigin, sourceID) VALUES ('Goblin', 'standard', NULL, (SELECT sourceID FROM Source WHERE sourceAbbrev = 'SRD 5.2.1'))
  ON CONFLICT (languageName) DO UPDATE SET languageKind = excluded.languageKind, languageOrigin = excluded.languageOrigin, sourceID = excluded.sourceID;
INSERT INTO Language (languageName, languageKind, languageOrigin, sourceID) VALUES ('Halfling', 'standard', NULL, (SELECT sourceID FROM Source WHERE sourceAbbrev = 'SRD 5.2.1'))
  ON CONFLICT (languageName) DO UPDATE SET languageKind = excluded.languageKind, languageOrigin = excluded.languageOrigin, sourceID = excluded.sourceID;
INSERT INTO Language (languageName, languageKind, languageOrigin, sourceID) VALUES ('Orc', 'standard', NULL, (SELECT sourceID FROM Source WHERE sourceAbbrev = 'SRD 5.2.1'))
  ON CONFLICT (languageName) DO UPDATE SET languageKind = excluded.languageKind, languageOrigin = excluded.languageOrigin, sourceID = excluded.sourceID;
INSERT INTO Language (languageName, languageKind, languageOrigin, sourceID) VALUES ('Abyssal', 'rare', NULL, (SELECT sourceID FROM Source WHERE sourceAbbrev = 'SRD 5.2.1'))
  ON CONFLICT (languageName) DO UPDATE SET languageKind = excluded.languageKind, languageOrigin = excluded.languageOrigin, sourceID = excluded.sourceID;
INSERT INTO Language (languageName, languageKind, languageOrigin, sourceID) VALUES ('Celestial', 'rare', NULL, (SELECT sourceID FROM Source WHERE sourceAbbrev = 'SRD 5.2.1'))
  ON CONFLICT (languageName) DO UPDATE SET languageKind = excluded.languageKind, languageOrigin = excluded.languageOrigin, sourceID = excluded.sourceID;
INSERT INTO Language (languageName, languageKind, languageOrigin, sourceID) VALUES ('Deep Speech', 'rare', NULL, (SELECT sourceID FROM Source WHERE sourceAbbrev = 'SRD 5.2.1'))
  ON CONFLICT (languageName) DO UPDATE SET languageKind = excluded.languageKind, languageOrigin = excluded.languageOrigin, sourceID = excluded.sourceID;
INSERT INTO Language (languageName, languageKind, languageOrigin, sourceID) VALUES ('Druidic', 'standard', NULL, (SELECT sourceID FROM Source WHERE sourceAbbrev = 'SRD 5.2.1'))
  ON CONFLICT (languageName) DO UPDATE SET languageKind = excluded.languageKind, languageOrigin = excluded.languageOrigin, sourceID = excluded.sourceID;
INSERT INTO Language (languageName, languageKind, languageOrigin, sourceID) VALUES ('Infernal', 'rare', NULL, (SELECT sourceID FROM Source WHERE sourceAbbrev = 'SRD 5.2.1'))
  ON CONFLICT (languageName) DO UPDATE SET languageKind = excluded.languageKind, languageOrigin = excluded.languageOrigin, sourceID = excluded.sourceID;
INSERT INTO Language (languageName, languageKind, languageOrigin, sourceID) VALUES ('Primordial', 'rare', 'Primordial includes the Aquan, Auran, Ignan, and Terran dialects. Creatures that know one of these dialects can communicate with those that know a different one.', (SELECT sourceID FROM Source WHERE sourceAbbrev = 'SRD 5.2.1'))
  ON CONFLICT (languageName) DO UPDATE SET languageKind = excluded.languageKind, languageOrigin = excluded.languageOrigin, sourceID = excluded.sourceID;
INSERT INTO Language (languageName, languageKind, languageOrigin, sourceID) VALUES ('Sylvan', 'rare', NULL, (SELECT sourceID FROM Source WHERE sourceAbbrev = 'SRD 5.2.1'))
  ON CONFLICT (languageName) DO UPDATE SET languageKind = excluded.languageKind, languageOrigin = excluded.languageOrigin, sourceID = excluded.sourceID;
INSERT INTO Language (languageName, languageKind, languageOrigin, sourceID) VALUES ('Thieves'' Cant', 'rare', NULL, (SELECT sourceID FROM Source WHERE sourceAbbrev = 'SRD 5.2.1'))
  ON CONFLICT (languageName) DO UPDATE SET languageKind = excluded.languageKind, languageOrigin = excluded.languageOrigin, sourceID = excluded.sourceID;
INSERT INTO Language (languageName, languageKind, languageOrigin, sourceID) VALUES ('Undercommon', 'rare', NULL, (SELECT sourceID FROM Source WHERE sourceAbbrev = 'SRD 5.2.1'))
  ON CONFLICT (languageName) DO UPDATE SET languageKind = excluded.languageKind, languageOrigin = excluded.languageOrigin, sourceID = excluded.sourceID;
INSERT INTO Denomination (denomKey, denomName, denomLabel, valueCp, sortOrder, active) VALUES ('pp', 'platinum', 'Platinum', 1000, 1, 1)
  ON CONFLICT (denomKey) DO UPDATE SET denomName = excluded.denomName, denomLabel = excluded.denomLabel, valueCp = excluded.valueCp, sortOrder = excluded.sortOrder, active = excluded.active;
INSERT INTO Denomination (denomKey, denomName, denomLabel, valueCp, sortOrder, active) VALUES ('gp', 'gold', 'Gold', 100, 2, 1)
  ON CONFLICT (denomKey) DO UPDATE SET denomName = excluded.denomName, denomLabel = excluded.denomLabel, valueCp = excluded.valueCp, sortOrder = excluded.sortOrder, active = excluded.active;
INSERT INTO Denomination (denomKey, denomName, denomLabel, valueCp, sortOrder, active) VALUES ('ep', 'electrum', 'Electrum', 50, 3, 0)
  ON CONFLICT (denomKey) DO UPDATE SET denomName = excluded.denomName, denomLabel = excluded.denomLabel, valueCp = excluded.valueCp, sortOrder = excluded.sortOrder, active = excluded.active;
INSERT INTO Denomination (denomKey, denomName, denomLabel, valueCp, sortOrder, active) VALUES ('sp', 'silver', 'Silver', 10, 4, 1)
  ON CONFLICT (denomKey) DO UPDATE SET denomName = excluded.denomName, denomLabel = excluded.denomLabel, valueCp = excluded.valueCp, sortOrder = excluded.sortOrder, active = excluded.active;
INSERT INTO Denomination (denomKey, denomName, denomLabel, valueCp, sortOrder, active) VALUES ('cp', 'copper', 'Copper', 1, 5, 1)
  ON CONFLICT (denomKey) DO UPDATE SET denomName = excluded.denomName, denomLabel = excluded.denomLabel, valueCp = excluded.valueCp, sortOrder = excluded.sortOrder, active = excluded.active;
INSERT INTO Rarity (rarityName, raritySlug, sortOrder, valueGp, craftDays, craftCostGp) VALUES ('Common', 'common', 1, 100, 5, 50)
  ON CONFLICT (rarityName) DO UPDATE SET raritySlug = excluded.raritySlug, sortOrder = excluded.sortOrder, valueGp = excluded.valueGp, craftDays = excluded.craftDays, craftCostGp = excluded.craftCostGp;
INSERT INTO Rarity (rarityName, raritySlug, sortOrder, valueGp, craftDays, craftCostGp) VALUES ('Uncommon', 'uncommon', 2, 400, 10, 200)
  ON CONFLICT (rarityName) DO UPDATE SET raritySlug = excluded.raritySlug, sortOrder = excluded.sortOrder, valueGp = excluded.valueGp, craftDays = excluded.craftDays, craftCostGp = excluded.craftCostGp;
INSERT INTO Rarity (rarityName, raritySlug, sortOrder, valueGp, craftDays, craftCostGp) VALUES ('Rare', 'rare', 3, 4000, 50, 2000)
  ON CONFLICT (rarityName) DO UPDATE SET raritySlug = excluded.raritySlug, sortOrder = excluded.sortOrder, valueGp = excluded.valueGp, craftDays = excluded.craftDays, craftCostGp = excluded.craftCostGp;
INSERT INTO Rarity (rarityName, raritySlug, sortOrder, valueGp, craftDays, craftCostGp) VALUES ('Very Rare', 'very-rare', 4, 40000, 125, 20000)
  ON CONFLICT (rarityName) DO UPDATE SET raritySlug = excluded.raritySlug, sortOrder = excluded.sortOrder, valueGp = excluded.valueGp, craftDays = excluded.craftDays, craftCostGp = excluded.craftCostGp;
INSERT INTO Rarity (rarityName, raritySlug, sortOrder, valueGp, craftDays, craftCostGp) VALUES ('Legendary', 'legendary', 5, 200000, 250, 100000)
  ON CONFLICT (rarityName) DO UPDATE SET raritySlug = excluded.raritySlug, sortOrder = excluded.sortOrder, valueGp = excluded.valueGp, craftDays = excluded.craftDays, craftCostGp = excluded.craftCostGp;
INSERT INTO Rarity (rarityName, raritySlug, sortOrder, valueGp, craftDays, craftCostGp) VALUES ('Artifact', 'artifact', 6, NULL, NULL, NULL)
  ON CONFLICT (rarityName) DO UPDATE SET raritySlug = excluded.raritySlug, sortOrder = excluded.sortOrder, valueGp = excluded.valueGp, craftDays = excluded.craftDays, craftCostGp = excluded.craftCostGp;
INSERT INTO ItemCategory (categoryName, categorySlug) VALUES ('Armor', 'armor')
  ON CONFLICT (categoryName) DO UPDATE SET categorySlug = excluded.categorySlug;
INSERT INTO ItemCategory (categoryName, categorySlug) VALUES ('Potion', 'potion')
  ON CONFLICT (categoryName) DO UPDATE SET categorySlug = excluded.categorySlug;
INSERT INTO ItemCategory (categoryName, categorySlug) VALUES ('Ring', 'ring')
  ON CONFLICT (categoryName) DO UPDATE SET categorySlug = excluded.categorySlug;
INSERT INTO ItemCategory (categoryName, categorySlug) VALUES ('Rod', 'rod')
  ON CONFLICT (categoryName) DO UPDATE SET categorySlug = excluded.categorySlug;
INSERT INTO ItemCategory (categoryName, categorySlug) VALUES ('Scroll', 'scroll')
  ON CONFLICT (categoryName) DO UPDATE SET categorySlug = excluded.categorySlug;
INSERT INTO ItemCategory (categoryName, categorySlug) VALUES ('Staff', 'staff')
  ON CONFLICT (categoryName) DO UPDATE SET categorySlug = excluded.categorySlug;
INSERT INTO ItemCategory (categoryName, categorySlug) VALUES ('Wand', 'wand')
  ON CONFLICT (categoryName) DO UPDATE SET categorySlug = excluded.categorySlug;
INSERT INTO ItemCategory (categoryName, categorySlug) VALUES ('Weapon', 'weapon')
  ON CONFLICT (categoryName) DO UPDATE SET categorySlug = excluded.categorySlug;
INSERT INTO ItemCategory (categoryName, categorySlug) VALUES ('Wondrous Item', 'wondrous-item')
  ON CONFLICT (categoryName) DO UPDATE SET categorySlug = excluded.categorySlug;
INSERT INTO MagicSchool (schoolName) VALUES ('Abjuration')
  ON CONFLICT (schoolName) DO NOTHING;
INSERT INTO MagicSchool (schoolName) VALUES ('Conjuration')
  ON CONFLICT (schoolName) DO NOTHING;
INSERT INTO MagicSchool (schoolName) VALUES ('Divination')
  ON CONFLICT (schoolName) DO NOTHING;
INSERT INTO MagicSchool (schoolName) VALUES ('Enchantment')
  ON CONFLICT (schoolName) DO NOTHING;
INSERT INTO MagicSchool (schoolName) VALUES ('Evocation')
  ON CONFLICT (schoolName) DO NOTHING;
INSERT INTO MagicSchool (schoolName) VALUES ('Illusion')
  ON CONFLICT (schoolName) DO NOTHING;
INSERT INTO MagicSchool (schoolName) VALUES ('Necromancy')
  ON CONFLICT (schoolName) DO NOTHING;
INSERT INTO MagicSchool (schoolName) VALUES ('Transmutation')
  ON CONFLICT (schoolName) DO NOTHING;
INSERT INTO ChallengeRating (crValue, crLabel, xp, proficiencyBonus) VALUES (0, '0', 10, 2)
  ON CONFLICT (crValue) DO UPDATE SET crLabel = excluded.crLabel, xp = excluded.xp, proficiencyBonus = excluded.proficiencyBonus;
INSERT INTO ChallengeRating (crValue, crLabel, xp, proficiencyBonus) VALUES (1, '1', 200, 2)
  ON CONFLICT (crValue) DO UPDATE SET crLabel = excluded.crLabel, xp = excluded.xp, proficiencyBonus = excluded.proficiencyBonus;
INSERT INTO ChallengeRating (crValue, crLabel, xp, proficiencyBonus) VALUES (2, '2', 450, 2)
  ON CONFLICT (crValue) DO UPDATE SET crLabel = excluded.crLabel, xp = excluded.xp, proficiencyBonus = excluded.proficiencyBonus;
INSERT INTO ChallengeRating (crValue, crLabel, xp, proficiencyBonus) VALUES (3, '3', 700, 2)
  ON CONFLICT (crValue) DO UPDATE SET crLabel = excluded.crLabel, xp = excluded.xp, proficiencyBonus = excluded.proficiencyBonus;
INSERT INTO ChallengeRating (crValue, crLabel, xp, proficiencyBonus) VALUES (4, '4', 1100, 2)
  ON CONFLICT (crValue) DO UPDATE SET crLabel = excluded.crLabel, xp = excluded.xp, proficiencyBonus = excluded.proficiencyBonus;
INSERT INTO ChallengeRating (crValue, crLabel, xp, proficiencyBonus) VALUES (5, '5', 1800, 3)
  ON CONFLICT (crValue) DO UPDATE SET crLabel = excluded.crLabel, xp = excluded.xp, proficiencyBonus = excluded.proficiencyBonus;
INSERT INTO ChallengeRating (crValue, crLabel, xp, proficiencyBonus) VALUES (6, '6', 2300, 3)
  ON CONFLICT (crValue) DO UPDATE SET crLabel = excluded.crLabel, xp = excluded.xp, proficiencyBonus = excluded.proficiencyBonus;
INSERT INTO ChallengeRating (crValue, crLabel, xp, proficiencyBonus) VALUES (7, '7', 2900, 3)
  ON CONFLICT (crValue) DO UPDATE SET crLabel = excluded.crLabel, xp = excluded.xp, proficiencyBonus = excluded.proficiencyBonus;
INSERT INTO ChallengeRating (crValue, crLabel, xp, proficiencyBonus) VALUES (8, '8', 3900, 3)
  ON CONFLICT (crValue) DO UPDATE SET crLabel = excluded.crLabel, xp = excluded.xp, proficiencyBonus = excluded.proficiencyBonus;
INSERT INTO ChallengeRating (crValue, crLabel, xp, proficiencyBonus) VALUES (9, '9', 5000, 4)
  ON CONFLICT (crValue) DO UPDATE SET crLabel = excluded.crLabel, xp = excluded.xp, proficiencyBonus = excluded.proficiencyBonus;
INSERT INTO ChallengeRating (crValue, crLabel, xp, proficiencyBonus) VALUES (10, '10', 5900, 4)
  ON CONFLICT (crValue) DO UPDATE SET crLabel = excluded.crLabel, xp = excluded.xp, proficiencyBonus = excluded.proficiencyBonus;
INSERT INTO ChallengeRating (crValue, crLabel, xp, proficiencyBonus) VALUES (11, '11', 7200, 4)
  ON CONFLICT (crValue) DO UPDATE SET crLabel = excluded.crLabel, xp = excluded.xp, proficiencyBonus = excluded.proficiencyBonus;
INSERT INTO ChallengeRating (crValue, crLabel, xp, proficiencyBonus) VALUES (12, '12', 8400, 4)
  ON CONFLICT (crValue) DO UPDATE SET crLabel = excluded.crLabel, xp = excluded.xp, proficiencyBonus = excluded.proficiencyBonus;
INSERT INTO ChallengeRating (crValue, crLabel, xp, proficiencyBonus) VALUES (13, '13', 10000, 5)
  ON CONFLICT (crValue) DO UPDATE SET crLabel = excluded.crLabel, xp = excluded.xp, proficiencyBonus = excluded.proficiencyBonus;
INSERT INTO ChallengeRating (crValue, crLabel, xp, proficiencyBonus) VALUES (14, '14', 11500, 5)
  ON CONFLICT (crValue) DO UPDATE SET crLabel = excluded.crLabel, xp = excluded.xp, proficiencyBonus = excluded.proficiencyBonus;
INSERT INTO ChallengeRating (crValue, crLabel, xp, proficiencyBonus) VALUES (15, '15', 13000, 5)
  ON CONFLICT (crValue) DO UPDATE SET crLabel = excluded.crLabel, xp = excluded.xp, proficiencyBonus = excluded.proficiencyBonus;
INSERT INTO ChallengeRating (crValue, crLabel, xp, proficiencyBonus) VALUES (16, '16', 15000, 5)
  ON CONFLICT (crValue) DO UPDATE SET crLabel = excluded.crLabel, xp = excluded.xp, proficiencyBonus = excluded.proficiencyBonus;
INSERT INTO ChallengeRating (crValue, crLabel, xp, proficiencyBonus) VALUES (17, '17', 18000, 6)
  ON CONFLICT (crValue) DO UPDATE SET crLabel = excluded.crLabel, xp = excluded.xp, proficiencyBonus = excluded.proficiencyBonus;
INSERT INTO ChallengeRating (crValue, crLabel, xp, proficiencyBonus) VALUES (18, '18', 20000, 6)
  ON CONFLICT (crValue) DO UPDATE SET crLabel = excluded.crLabel, xp = excluded.xp, proficiencyBonus = excluded.proficiencyBonus;
INSERT INTO ChallengeRating (crValue, crLabel, xp, proficiencyBonus) VALUES (19, '19', 22000, 6)
  ON CONFLICT (crValue) DO UPDATE SET crLabel = excluded.crLabel, xp = excluded.xp, proficiencyBonus = excluded.proficiencyBonus;
INSERT INTO ChallengeRating (crValue, crLabel, xp, proficiencyBonus) VALUES (20, '20', 25000, 6)
  ON CONFLICT (crValue) DO UPDATE SET crLabel = excluded.crLabel, xp = excluded.xp, proficiencyBonus = excluded.proficiencyBonus;
INSERT INTO ChallengeRating (crValue, crLabel, xp, proficiencyBonus) VALUES (21, '21', 33000, 7)
  ON CONFLICT (crValue) DO UPDATE SET crLabel = excluded.crLabel, xp = excluded.xp, proficiencyBonus = excluded.proficiencyBonus;
INSERT INTO ChallengeRating (crValue, crLabel, xp, proficiencyBonus) VALUES (22, '22', 41000, 7)
  ON CONFLICT (crValue) DO UPDATE SET crLabel = excluded.crLabel, xp = excluded.xp, proficiencyBonus = excluded.proficiencyBonus;
INSERT INTO ChallengeRating (crValue, crLabel, xp, proficiencyBonus) VALUES (23, '23', 50000, 7)
  ON CONFLICT (crValue) DO UPDATE SET crLabel = excluded.crLabel, xp = excluded.xp, proficiencyBonus = excluded.proficiencyBonus;
INSERT INTO ChallengeRating (crValue, crLabel, xp, proficiencyBonus) VALUES (24, '24', 62000, 7)
  ON CONFLICT (crValue) DO UPDATE SET crLabel = excluded.crLabel, xp = excluded.xp, proficiencyBonus = excluded.proficiencyBonus;
INSERT INTO ChallengeRating (crValue, crLabel, xp, proficiencyBonus) VALUES (25, '25', 75000, 8)
  ON CONFLICT (crValue) DO UPDATE SET crLabel = excluded.crLabel, xp = excluded.xp, proficiencyBonus = excluded.proficiencyBonus;
INSERT INTO ChallengeRating (crValue, crLabel, xp, proficiencyBonus) VALUES (26, '26', 90000, 8)
  ON CONFLICT (crValue) DO UPDATE SET crLabel = excluded.crLabel, xp = excluded.xp, proficiencyBonus = excluded.proficiencyBonus;
INSERT INTO ChallengeRating (crValue, crLabel, xp, proficiencyBonus) VALUES (27, '27', 105000, 8)
  ON CONFLICT (crValue) DO UPDATE SET crLabel = excluded.crLabel, xp = excluded.xp, proficiencyBonus = excluded.proficiencyBonus;
INSERT INTO ChallengeRating (crValue, crLabel, xp, proficiencyBonus) VALUES (28, '28', 120000, 8)
  ON CONFLICT (crValue) DO UPDATE SET crLabel = excluded.crLabel, xp = excluded.xp, proficiencyBonus = excluded.proficiencyBonus;
INSERT INTO ChallengeRating (crValue, crLabel, xp, proficiencyBonus) VALUES (29, '29', 135000, 9)
  ON CONFLICT (crValue) DO UPDATE SET crLabel = excluded.crLabel, xp = excluded.xp, proficiencyBonus = excluded.proficiencyBonus;
INSERT INTO ChallengeRating (crValue, crLabel, xp, proficiencyBonus) VALUES (30, '30', 155000, 9)
  ON CONFLICT (crValue) DO UPDATE SET crLabel = excluded.crLabel, xp = excluded.xp, proficiencyBonus = excluded.proficiencyBonus;
INSERT INTO ChallengeRating (crValue, crLabel, xp, proficiencyBonus) VALUES (0.125, '1/8', 25, 2)
  ON CONFLICT (crValue) DO UPDATE SET crLabel = excluded.crLabel, xp = excluded.xp, proficiencyBonus = excluded.proficiencyBonus;
INSERT INTO ChallengeRating (crValue, crLabel, xp, proficiencyBonus) VALUES (0.25, '1/4', 50, 2)
  ON CONFLICT (crValue) DO UPDATE SET crLabel = excluded.crLabel, xp = excluded.xp, proficiencyBonus = excluded.proficiencyBonus;
INSERT INTO ChallengeRating (crValue, crLabel, xp, proficiencyBonus) VALUES (0.5, '1/2', 100, 2)
  ON CONFLICT (crValue) DO UPDATE SET crLabel = excluded.crLabel, xp = excluded.xp, proficiencyBonus = excluded.proficiencyBonus;
INSERT INTO CharacterLevel (level, xpRequired, proficiencyBonus) VALUES (1, 0, 2)
  ON CONFLICT (level) DO UPDATE SET xpRequired = excluded.xpRequired, proficiencyBonus = excluded.proficiencyBonus;
INSERT INTO CharacterLevel (level, xpRequired, proficiencyBonus) VALUES (2, 300, 2)
  ON CONFLICT (level) DO UPDATE SET xpRequired = excluded.xpRequired, proficiencyBonus = excluded.proficiencyBonus;
INSERT INTO CharacterLevel (level, xpRequired, proficiencyBonus) VALUES (3, 900, 2)
  ON CONFLICT (level) DO UPDATE SET xpRequired = excluded.xpRequired, proficiencyBonus = excluded.proficiencyBonus;
INSERT INTO CharacterLevel (level, xpRequired, proficiencyBonus) VALUES (4, 2700, 2)
  ON CONFLICT (level) DO UPDATE SET xpRequired = excluded.xpRequired, proficiencyBonus = excluded.proficiencyBonus;
INSERT INTO CharacterLevel (level, xpRequired, proficiencyBonus) VALUES (5, 6500, 3)
  ON CONFLICT (level) DO UPDATE SET xpRequired = excluded.xpRequired, proficiencyBonus = excluded.proficiencyBonus;
INSERT INTO CharacterLevel (level, xpRequired, proficiencyBonus) VALUES (6, 14000, 3)
  ON CONFLICT (level) DO UPDATE SET xpRequired = excluded.xpRequired, proficiencyBonus = excluded.proficiencyBonus;
INSERT INTO CharacterLevel (level, xpRequired, proficiencyBonus) VALUES (7, 23000, 3)
  ON CONFLICT (level) DO UPDATE SET xpRequired = excluded.xpRequired, proficiencyBonus = excluded.proficiencyBonus;
INSERT INTO CharacterLevel (level, xpRequired, proficiencyBonus) VALUES (8, 34000, 3)
  ON CONFLICT (level) DO UPDATE SET xpRequired = excluded.xpRequired, proficiencyBonus = excluded.proficiencyBonus;
INSERT INTO CharacterLevel (level, xpRequired, proficiencyBonus) VALUES (9, 48000, 4)
  ON CONFLICT (level) DO UPDATE SET xpRequired = excluded.xpRequired, proficiencyBonus = excluded.proficiencyBonus;
INSERT INTO CharacterLevel (level, xpRequired, proficiencyBonus) VALUES (10, 64000, 4)
  ON CONFLICT (level) DO UPDATE SET xpRequired = excluded.xpRequired, proficiencyBonus = excluded.proficiencyBonus;
INSERT INTO CharacterLevel (level, xpRequired, proficiencyBonus) VALUES (11, 85000, 4)
  ON CONFLICT (level) DO UPDATE SET xpRequired = excluded.xpRequired, proficiencyBonus = excluded.proficiencyBonus;
INSERT INTO CharacterLevel (level, xpRequired, proficiencyBonus) VALUES (12, 100000, 4)
  ON CONFLICT (level) DO UPDATE SET xpRequired = excluded.xpRequired, proficiencyBonus = excluded.proficiencyBonus;
INSERT INTO CharacterLevel (level, xpRequired, proficiencyBonus) VALUES (13, 120000, 5)
  ON CONFLICT (level) DO UPDATE SET xpRequired = excluded.xpRequired, proficiencyBonus = excluded.proficiencyBonus;
INSERT INTO CharacterLevel (level, xpRequired, proficiencyBonus) VALUES (14, 140000, 5)
  ON CONFLICT (level) DO UPDATE SET xpRequired = excluded.xpRequired, proficiencyBonus = excluded.proficiencyBonus;
INSERT INTO CharacterLevel (level, xpRequired, proficiencyBonus) VALUES (15, 165000, 5)
  ON CONFLICT (level) DO UPDATE SET xpRequired = excluded.xpRequired, proficiencyBonus = excluded.proficiencyBonus;
INSERT INTO CharacterLevel (level, xpRequired, proficiencyBonus) VALUES (16, 195000, 5)
  ON CONFLICT (level) DO UPDATE SET xpRequired = excluded.xpRequired, proficiencyBonus = excluded.proficiencyBonus;
INSERT INTO CharacterLevel (level, xpRequired, proficiencyBonus) VALUES (17, 225000, 6)
  ON CONFLICT (level) DO UPDATE SET xpRequired = excluded.xpRequired, proficiencyBonus = excluded.proficiencyBonus;
INSERT INTO CharacterLevel (level, xpRequired, proficiencyBonus) VALUES (18, 265000, 6)
  ON CONFLICT (level) DO UPDATE SET xpRequired = excluded.xpRequired, proficiencyBonus = excluded.proficiencyBonus;
INSERT INTO CharacterLevel (level, xpRequired, proficiencyBonus) VALUES (19, 305000, 6)
  ON CONFLICT (level) DO UPDATE SET xpRequired = excluded.xpRequired, proficiencyBonus = excluded.proficiencyBonus;
INSERT INTO CharacterLevel (level, xpRequired, proficiencyBonus) VALUES (20, 355000, 6)
  ON CONFLICT (level) DO UPDATE SET xpRequired = excluded.xpRequired, proficiencyBonus = excluded.proficiencyBonus;
INSERT INTO WeaponProperty (weaponPropertyName, weaponPropertyDescription) VALUES ('Ammunition', 'You can use a weapon that has the Ammunition property to make a ranged attack only if you have ammunition to fire from it. The type of ammunition required is specified with the weapon''s range. Each attack expends one piece of ammunition. Drawing the ammunition is part of the attack (you need a free hand to load a one-handed weapon). After a fight, you can spend 1 minute to recover half the ammunition (round down) you used in the fight; the rest is lost.')
  ON CONFLICT (weaponPropertyName) DO UPDATE SET weaponPropertyDescription = excluded.weaponPropertyDescription;
INSERT INTO WeaponProperty (weaponPropertyName, weaponPropertyDescription) VALUES ('Finesse', 'When making an attack with a Finesse weapon, use your choice of your Strength or Dexterity modifier for the attack and damage rolls. You must use the same modifier for both rolls.')
  ON CONFLICT (weaponPropertyName) DO UPDATE SET weaponPropertyDescription = excluded.weaponPropertyDescription;
INSERT INTO WeaponProperty (weaponPropertyName, weaponPropertyDescription) VALUES ('Heavy', 'You have Disadvantage on attack rolls with a Heavy weapon if it''s a Melee weapon and your Strength score isn''t at least 13 or if it''s a Ranged weapon and your Dexterity score isn''t at least 13.')
  ON CONFLICT (weaponPropertyName) DO UPDATE SET weaponPropertyDescription = excluded.weaponPropertyDescription;
INSERT INTO WeaponProperty (weaponPropertyName, weaponPropertyDescription) VALUES ('Light', 'When you take the Attack action on your turn and attack with a Light weapon, you can make one extra attack as a Bonus Action later on the same turn. That extra attack must be made with a different Light weapon, and you don''t add your ability modifier to the extra attack''s damage unless that modifier is negative. For example, you can attack with a Shortsword in one hand and a Dagger in the other using the Attack action and a Bonus Action, but you don''t add your Strength or Dexterity modifier to the damage roll of the Bonus Action unless that modifier is negative.')
  ON CONFLICT (weaponPropertyName) DO UPDATE SET weaponPropertyDescription = excluded.weaponPropertyDescription;
INSERT INTO WeaponProperty (weaponPropertyName, weaponPropertyDescription) VALUES ('Loading', 'You can fire only one piece of ammunition from a Loading weapon when you use an action, a Bonus Action, or a Reaction to fire it, regardless of the number of attacks you can normally make.')
  ON CONFLICT (weaponPropertyName) DO UPDATE SET weaponPropertyDescription = excluded.weaponPropertyDescription;
INSERT INTO WeaponProperty (weaponPropertyName, weaponPropertyDescription) VALUES ('Range', 'A Range weapon has a range in parentheses after the Ammunition or Thrown property. The range lists two numbers. The first is the weapon''s normal range in feet, and the second is the weapon''s long range. When attacking a target beyond normal range, you have Disadvantage on the attack roll. You can''t attack a target beyond the long range.')
  ON CONFLICT (weaponPropertyName) DO UPDATE SET weaponPropertyDescription = excluded.weaponPropertyDescription;
INSERT INTO WeaponProperty (weaponPropertyName, weaponPropertyDescription) VALUES ('Reach', 'A Reach weapon adds 5 feet to your reach when you attack with it, as well as when determining your reach for Opportunity Attacks with it.')
  ON CONFLICT (weaponPropertyName) DO UPDATE SET weaponPropertyDescription = excluded.weaponPropertyDescription;
INSERT INTO WeaponProperty (weaponPropertyName, weaponPropertyDescription) VALUES ('Thrown', 'If a weapon has the Thrown property, you can throw the weapon to make a ranged attack, and you can draw that weapon as part of the attack. If the weapon is a Melee weapon, use the same ability modifier for the attack and damage rolls that you use for a melee attack with that weapon.')
  ON CONFLICT (weaponPropertyName) DO UPDATE SET weaponPropertyDescription = excluded.weaponPropertyDescription;
INSERT INTO WeaponProperty (weaponPropertyName, weaponPropertyDescription) VALUES ('Two-Handed', 'A Two-Handed weapon requires two hands when you attack with it.')
  ON CONFLICT (weaponPropertyName) DO UPDATE SET weaponPropertyDescription = excluded.weaponPropertyDescription;
INSERT INTO WeaponProperty (weaponPropertyName, weaponPropertyDescription) VALUES ('Versatile', 'A Versatile weapon can be used with one or two hands. A damage value in parentheses appears with the property. The weapon deals that damage when used with two hands to make a melee attack.')
  ON CONFLICT (weaponPropertyName) DO UPDATE SET weaponPropertyDescription = excluded.weaponPropertyDescription;
INSERT INTO WeaponMastery (masteryName, masteryDescription) VALUES ('Cleave', 'If you hit a creature with a melee attack roll using this weapon, you can make a melee attack roll with the weapon against a second creature within 5 feet of the first that is also within your reach. On a hit, the second creature takes the weapon''s damage, but don''t add your ability modifier to that damage unless that modifier is negative. You can make this extra attack only once per turn.')
  ON CONFLICT (masteryName) DO UPDATE SET masteryDescription = excluded.masteryDescription;
INSERT INTO WeaponMastery (masteryName, masteryDescription) VALUES ('Graze', 'If your attack roll with this weapon misses a creature, you can deal damage to that creature equal to the ability modifier you used to make the attack roll. This damage is the same type dealt by the weapon, and the damage can be increased only by increasing the ability modifier.')
  ON CONFLICT (masteryName) DO UPDATE SET masteryDescription = excluded.masteryDescription;
INSERT INTO WeaponMastery (masteryName, masteryDescription) VALUES ('Nick', 'When you make the extra attack of the Light property, you can make it as part of the Attack action instead of as a Bonus Action. You can make this extra attack only once per turn.')
  ON CONFLICT (masteryName) DO UPDATE SET masteryDescription = excluded.masteryDescription;
INSERT INTO WeaponMastery (masteryName, masteryDescription) VALUES ('Push', 'If you hit a creature with this weapon, you can push the creature up to 10 feet straight away from yourself if it is Large or smaller.')
  ON CONFLICT (masteryName) DO UPDATE SET masteryDescription = excluded.masteryDescription;
INSERT INTO WeaponMastery (masteryName, masteryDescription) VALUES ('Sap', 'If you hit a creature with this weapon, that creature has Disadvantage on its next attack roll before the start of your next turn.')
  ON CONFLICT (masteryName) DO UPDATE SET masteryDescription = excluded.masteryDescription;
INSERT INTO WeaponMastery (masteryName, masteryDescription) VALUES ('Slow', 'If you hit a creature with this weapon and deal damage to it, you can reduce its Speed by 10 feet until the start of your next turn. If the creature is hit more than once by weapons that have this property, the Speed reduction doesn''t exceed 10 feet.')
  ON CONFLICT (masteryName) DO UPDATE SET masteryDescription = excluded.masteryDescription;
INSERT INTO WeaponMastery (masteryName, masteryDescription) VALUES ('Topple', 'If you hit a creature with this weapon, you can force the creature to make a Constitution saving throw (DC 8 plus the ability modifier used to make the attack roll and your Proficiency Bonus). On a failed save, the creature has the Prone condition.')
  ON CONFLICT (masteryName) DO UPDATE SET masteryDescription = excluded.masteryDescription;
INSERT INTO WeaponMastery (masteryName, masteryDescription) VALUES ('Vex', 'If you hit a creature with this weapon and deal damage to the creature, you have Advantage on your next attack roll against that creature before the end of your next turn.')
  ON CONFLICT (masteryName) DO UPDATE SET masteryDescription = excluded.masteryDescription;
INSERT INTO Poison (poisonName, poisonType, costCp, poisonDescription, sourceID) VALUES ('Assassin''s Blood', 'ingested', NULL, 'A creature subjected to Assassin''s Blood makes a DC 10 Constitution saving throw. On a failed save, the creature takes 6 (1d12) Poison damage and has the Poisoned condition for 24 hours. On a successful save, the creature takes half as much damage only.', (SELECT sourceID FROM Source WHERE sourceAbbrev = 'SRD 5.2.1'))
  ON CONFLICT (poisonName) DO UPDATE SET poisonType = excluded.poisonType, costCp = excluded.costCp, poisonDescription = excluded.poisonDescription, sourceID = excluded.sourceID;
INSERT INTO Poison (poisonName, poisonType, costCp, poisonDescription, sourceID) VALUES ('Burnt Othur Fumes', 'inhaled', NULL, 'A creature subjected to Burnt Othur Fumes must succeed on a DC 13 Constitution saving throw or take 10 (3d6) Poison damage, and it must repeat the save at the start of each of its turns. On each successive failed save, the creature takes 3 (1d6) Poison damage. After three successful saves, the poison ends.', (SELECT sourceID FROM Source WHERE sourceAbbrev = 'SRD 5.2.1'))
  ON CONFLICT (poisonName) DO UPDATE SET poisonType = excluded.poisonType, costCp = excluded.costCp, poisonDescription = excluded.poisonDescription, sourceID = excluded.sourceID;
INSERT INTO Poison (poisonName, poisonType, costCp, poisonDescription, sourceID) VALUES ('Crawler Mucus', 'contact', NULL, 'A creature subjected to Crawler Mucus must succeed on a DC 13 Constitution saving throw or have the Poisoned condition for 1 minute. The creature also has the Paralyzed condition while Poisoned in this way. The creature repeats the save at the end of each of its turns, ending the effect on itself on a success.', (SELECT sourceID FROM Source WHERE sourceAbbrev = 'SRD 5.2.1'))
  ON CONFLICT (poisonName) DO UPDATE SET poisonType = excluded.poisonType, costCp = excluded.costCp, poisonDescription = excluded.poisonDescription, sourceID = excluded.sourceID;
INSERT INTO Poison (poisonName, poisonType, costCp, poisonDescription, sourceID) VALUES ('Essence of Ether', 'inhaled', NULL, 'A creature subjected to Essence of Ether must succeed on a DC 15 Constitution saving throw or have the Poisoned condition for 8 hours. The creature also has the Unconscious condition while Poisoned in this way. The creature wakes up if it takes damage or if another creature takes an action to shake it awake.', (SELECT sourceID FROM Source WHERE sourceAbbrev = 'SRD 5.2.1'))
  ON CONFLICT (poisonName) DO UPDATE SET poisonType = excluded.poisonType, costCp = excluded.costCp, poisonDescription = excluded.poisonDescription, sourceID = excluded.sourceID;
INSERT INTO Poison (poisonName, poisonType, costCp, poisonDescription, sourceID) VALUES ('Malice', 'inhaled', NULL, 'A creature subjected to Malice must succeed on a DC 15 Constitution saving throw or have the Poisoned condition for 1 hour. The creature also has the Blinded condition while Poisoned in this way.', (SELECT sourceID FROM Source WHERE sourceAbbrev = 'SRD 5.2.1'))
  ON CONFLICT (poisonName) DO UPDATE SET poisonType = excluded.poisonType, costCp = excluded.costCp, poisonDescription = excluded.poisonDescription, sourceID = excluded.sourceID;
INSERT INTO Poison (poisonName, poisonType, costCp, poisonDescription, sourceID) VALUES ('Midnight Tears', 'ingested', NULL, 'A creature that ingests Midnight Tears suffers no effect until the stroke of midnight. Any effect that ends the Poisoned condition neutralizes this poison. If the poison hasn''t been neutralized before midnight, the creature makes a DC 17 Constitution saving throw, taking 31 (9d6) Poison damage on a failed save or half as much damage on a successful one.', (SELECT sourceID FROM Source WHERE sourceAbbrev = 'SRD 5.2.1'))
  ON CONFLICT (poisonName) DO UPDATE SET poisonType = excluded.poisonType, costCp = excluded.costCp, poisonDescription = excluded.poisonDescription, sourceID = excluded.sourceID;
INSERT INTO Poison (poisonName, poisonType, costCp, poisonDescription, sourceID) VALUES ('Oil of Taggit', 'contact', NULL, 'A creature subjected to Oil of Taggit must succeed on a DC 13 Constitution saving throw or have the Poisoned condition for 24 hours. The creature also has the Unconscious condition while Poisoned in this way. It wakes up if it takes damage.', (SELECT sourceID FROM Source WHERE sourceAbbrev = 'SRD 5.2.1'))
  ON CONFLICT (poisonName) DO UPDATE SET poisonType = excluded.poisonType, costCp = excluded.costCp, poisonDescription = excluded.poisonDescription, sourceID = excluded.sourceID;
INSERT INTO Poison (poisonName, poisonType, costCp, poisonDescription, sourceID) VALUES ('Pale Tincture', 'ingested', NULL, 'A creature subjected to Pale Tincture must succeed on a DC 16 Constitution saving throw or take 3 (1d6) Poison damage and have the Poisoned condition. The Poisoned creature repeats the save every 24 hours, taking 3 (1d6) Poison damage on a failed save. The damage the poison deals can''t be healed by any means while the creature remains Poisoned. After seven successful saves against the poison, the creature is no longer Poisoned.', (SELECT sourceID FROM Source WHERE sourceAbbrev = 'SRD 5.2.1'))
  ON CONFLICT (poisonName) DO UPDATE SET poisonType = excluded.poisonType, costCp = excluded.costCp, poisonDescription = excluded.poisonDescription, sourceID = excluded.sourceID;
INSERT INTO Poison (poisonName, poisonType, costCp, poisonDescription, sourceID) VALUES ('Purple Worm Poison', 'injury', NULL, 'A creature subjected to Purple Worm Poison makes a DC 21 Constitution saving throw, taking 35 (10d6) Poison damage on a failed save or half as much damage on a successful one.', (SELECT sourceID FROM Source WHERE sourceAbbrev = 'SRD 5.2.1'))
  ON CONFLICT (poisonName) DO UPDATE SET poisonType = excluded.poisonType, costCp = excluded.costCp, poisonDescription = excluded.poisonDescription, sourceID = excluded.sourceID;
INSERT INTO Poison (poisonName, poisonType, costCp, poisonDescription, sourceID) VALUES ('Serpent Venom', 'injury', NULL, 'A creature subjected to Serpent Venom must succeed on a DC 11 Constitution saving throw, taking 10 (3d6) Poison damage on a failed save or half as much damage on a successful one.', (SELECT sourceID FROM Source WHERE sourceAbbrev = 'SRD 5.2.1'))
  ON CONFLICT (poisonName) DO UPDATE SET poisonType = excluded.poisonType, costCp = excluded.costCp, poisonDescription = excluded.poisonDescription, sourceID = excluded.sourceID;
INSERT INTO Poison (poisonName, poisonType, costCp, poisonDescription, sourceID) VALUES ('Spider''s Sting', 'injury', NULL, 'A creature subjected to Spider''s Sting must succeed on a DC 13 Constitution saving throw or have the Poisoned condition for 1 hour. If the creature fails the save by 5 or more, the creature also has the Unconscious condition while Poisoned in this way. The creature wakes up if it takes damage or if another creature takes an action to shake it awake.', (SELECT sourceID FROM Source WHERE sourceAbbrev = 'SRD 5.2.1'))
  ON CONFLICT (poisonName) DO UPDATE SET poisonType = excluded.poisonType, costCp = excluded.costCp, poisonDescription = excluded.poisonDescription, sourceID = excluded.sourceID;
INSERT INTO Poison (poisonName, poisonType, costCp, poisonDescription, sourceID) VALUES ('Torpor', 'ingested', NULL, 'A creature subjected to Torpor poison must succeed on a DC 15 Constitution saving throw or have the Poisoned condition for 4d6 hours. The creature''s Speed is halved while the creature is Poisoned in this way.', (SELECT sourceID FROM Source WHERE sourceAbbrev = 'SRD 5.2.1'))
  ON CONFLICT (poisonName) DO UPDATE SET poisonType = excluded.poisonType, costCp = excluded.costCp, poisonDescription = excluded.poisonDescription, sourceID = excluded.sourceID;
INSERT INTO Poison (poisonName, poisonType, costCp, poisonDescription, sourceID) VALUES ('Truth Serum', 'ingested', NULL, 'A creature subjected to Truth Serum must succeed on a DC 11 Constitution saving throw or have the Poisoned condition for 1 hour. The Poisoned creature can''t knowingly communicate a lie.', (SELECT sourceID FROM Source WHERE sourceAbbrev = 'SRD 5.2.1'))
  ON CONFLICT (poisonName) DO UPDATE SET poisonType = excluded.poisonType, costCp = excluded.costCp, poisonDescription = excluded.poisonDescription, sourceID = excluded.sourceID;
INSERT INTO Poison (poisonName, poisonType, costCp, poisonDescription, sourceID) VALUES ('Wyvern Poison', 'injury', NULL, 'A creature subjected to Wyvern Poison makes a DC 14 Constitution saving throw, taking 24 (7d6) Poison damage on a failed save or half as much damage on a successful one.', (SELECT sourceID FROM Source WHERE sourceAbbrev = 'SRD 5.2.1'))
  ON CONFLICT (poisonName) DO UPDATE SET poisonType = excluded.poisonType, costCp = excluded.costCp, poisonDescription = excluded.poisonDescription, sourceID = excluded.sourceID;
